runtime: python39

entrypoint: gunicorn -b :$PORT main:app

env_variables:
  PYTHONUNBUFFERED: 'true'

instance_class: F2

handlers:
  - url: /static
    static_dir: static/

  - url: /templates
    static_dir: templates/

  - url: /.*
    script: auto
